{{- if and .Values.gateway.enabled .Values.gateway.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ursula.gatewayFullname" . }}
  labels:
    {{- include "ursula.gatewayLabels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.gateway.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "ursula.gatewaySelectorLabels" . | nindent 6 }}
{{- end }}
