{{- if and .Values.indexer.enabled .Values.indexer.service.enabled -}}
{{- $root := . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ursula.indexerFullname" $root }}
  labels:
    {{- include "ursula.indexerLabels" $root | nindent 4 }}
  {{- with $root.Values.indexer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $root.Values.indexer.service.type }}
  ports:
    - name: http
      port: {{ $root.Values.indexer.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ursula.indexerSelectorLabels" $root | nindent 4 }}
{{- end }}
