{{- if and .Values.indexer.enabled .Values.indexer.podDisruptionBudget.enabled -}}
{{- $root := . -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ursula.indexerFullname" $root }}
  labels:
    {{- include "ursula.indexerLabels" $root | nindent 4 }}
spec:
  maxUnavailable: {{ $root.Values.indexer.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "ursula.indexerSelectorLabels" $root | nindent 6 }}
{{- end }}
