{{- if and (or .Values.coldStorage.enabled (.Values.snapshotStore.backend | eq "s3") .Values.indexer.enabled) (.Values.s3.credentials.existingSecret | not) (include "ursula.hasInlineS3Credentials" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ursula.s3SecretName" . | quote }}
  labels:
    {{- include "ursula.labels" . | nindent 4 }}
type: Opaque
data:
  "accessKeyId": {{ .Values.s3.credentials.accessKeyId | b64enc | quote }}
  "secretAccessKey": {{ .Values.s3.credentials.secretAccessKey | b64enc | quote }}
  {{- if .Values.s3.credentials.sessionToken }}
  "sessionToken": {{ .Values.s3.credentials.sessionToken | b64enc | quote }}
  {{- end }}
{{- end }}
