import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { buildAppHref, isInternalAppPath, navigateTo } from "../../utils/navigation";

type PagefindSubResult = {
  url: string;
  title: string;
  excerpt: string;
};

type PagefindResultData = {
  url: string;
  excerpt: string;
  meta: {
    title?: string;
  };
  sub_results: PagefindSubResult[];
};

type PagefindResult = {
  id: string;
  data: () => Promise<PagefindResultData>;
};

type Pagefind = {
  init: () => Promise<void>;
  search: (query: string) => Promise<{ results: PagefindResult[] }>;
};

type ResolvedResult = {
  id: string;
  url: string;
  title: string;
  excerpt: string;
  subResults: PagefindSubResult[];
};

/**
 * Pagefind returns excerpts with the matched terms pre-wrapped in `<mark>` tags.
 * Keep the HTML so they render with our Gruvbox highlight style; the excerpt
 * content comes from our own build-time content so it is safe to inject.
 */
function excerptHtml(excerpt: string | undefined) {
  if (!excerpt) return "";
  return excerpt;
}

function normalizeUrl(url: string) {
  if (!url) return "/";
  const trimmed = url.replace(/\.html$/, "").replace(/\/index$/, "");
  return trimmed || "/";
}

function isMacLike() {
  if (typeof navigator === "undefined") return false;
  return /Mac|iPhone|iPad|iPod/i.test(navigator.platform ?? navigator.userAgent ?? "");
}

function SearchModal() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<ResolvedResult[]>([]);
  const [status, setStatus] = useState<"idle" | "loading" | "ready" | "unavailable">("idle");
  const pagefindRef = useRef<Pagefind | null>(null);
  const inputRef = useRef<HTMLInputElement | null>(null);

  const shortcutLabel = useMemo(() => (isMacLike() ? "⌘K" : "Ctrl K"), []);

  const openModal = useCallback(() => setOpen(true), []);
  const closeModal = useCallback(() => {
    setOpen(false);
    setQuery("");
    setResults([]);
  }, []);

  // Global Cmd/Ctrl+K
  useEffect(() => {
    const handler = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
        event.preventDefault();
        setOpen((current) => !current);
      }
      if (event.key === "Escape") {
        setOpen(false);
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, []);

  // Load Pagefind when modal opens
  useEffect(() => {
    if (!open || pagefindRef.current || status === "loading" || status === "unavailable") {
      return;
    }

    setStatus("loading");
    (async () => {
      try {
        // Hide the import specifier from Rollup's static analyzer. The file is
        // generated by Pagefind at build time and served from the site root at
        // /pagefind/pagefind.js — not an ES module that Vite should bundle.
        const loadPagefind = new Function("return import('/pagefind/pagefind.js')") as () => Promise<Pagefind>;
        const module = await loadPagefind();
        await module.init();
        pagefindRef.current = module;
        setStatus("ready");
      } catch (error) {
        console.warn("Pagefind index not available (did you run `npm run build`?)", error);
        setStatus("unavailable");
      }
    })();
  }, [open, status]);

  // Focus input when modal opens
  useEffect(() => {
    if (open) {
      const frame = requestAnimationFrame(() => inputRef.current?.focus());
      return () => cancelAnimationFrame(frame);
    }
    return undefined;
  }, [open]);

  // Lock body scroll while modal is open
  useEffect(() => {
    if (!open) return undefined;
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = previous;
    };
  }, [open]);

  // Run search when query changes
  useEffect(() => {
    const pagefind = pagefindRef.current;
    if (!pagefind || status !== "ready") return;

    if (!query.trim()) {
      setResults([]);
      return;
    }

    let cancelled = false;
    (async () => {
      const { results: rawResults } = await pagefind.search(query);
      const resolved = await Promise.all(
        rawResults.slice(0, 8).map(async (result) => {
          const data = await result.data();
          return {
            id: result.id,
            url: normalizeUrl(data.url),
            title: data.meta.title ?? "Untitled",
            excerpt: excerptHtml(data.excerpt),
            subResults: data.sub_results ?? [],
          } satisfies ResolvedResult;
        }),
      );
      if (!cancelled) {
        setResults(resolved);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [query, status]);

  const handleResultClick = (url: string) => (event: React.MouseEvent<HTMLAnchorElement>) => {
    if (!isInternalAppPath(url)) return;
    event.preventDefault();
    closeModal();
    navigateTo(url);
  };

  const modal = !open ? null : (
    <div className="docs-search-overlay" role="dialog" aria-modal="true" aria-label="Search docs">
      <div
        className="docs-search-backdrop"
        onClick={closeModal}
        aria-hidden="true"
      />
      <div className="docs-search-panel">
        <div className="docs-search-input-row">
          <span className="docs-search-icon" aria-hidden="true">
            <svg width="16" height="16" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="9" cy="9" r="6" />
              <path d="m17 17-3.5-3.5" strokeLinecap="round" />
            </svg>
          </span>
          <input
            ref={inputRef}
            className="docs-search-input"
            type="search"
            placeholder="Search docs..."
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            autoComplete="off"
            spellCheck={false}
          />
          <button type="button" className="docs-search-close" onClick={closeModal} aria-label="Close search">
            <kbd>esc</kbd>
          </button>
        </div>

        <div className="docs-search-results">
          {status === "loading" && query && (
            <p className="docs-search-hint">Loading index...</p>
          )}

          {status === "unavailable" && (
            <p className="docs-search-hint">
              Search index not available. Run <code>npm run build</code> to generate it.
            </p>
          )}

          {status === "ready" && !query.trim() && (
            <p className="docs-search-hint">Start typing to search the documentation.</p>
          )}

          {status === "ready" && query.trim() && results.length === 0 && (
            <p className="docs-search-hint">No results for "{query}".</p>
          )}

          {results.map((result) => (
            <a
              key={result.id}
              className="docs-search-result"
              href={isInternalAppPath(result.url) ? buildAppHref(result.url) : result.url}
              onClick={handleResultClick(result.url)}
            >
              <div className="docs-search-result-title">{result.title}</div>
              {result.excerpt && (
                <div
                  className="docs-search-result-excerpt"
                  dangerouslySetInnerHTML={{ __html: result.excerpt }}
                />
              )}
              {result.subResults.length > 0 && (
                <ul className="docs-search-sub-results">
                  {result.subResults.slice(0, 3).map((sub) => (
                    <li key={sub.url}>
                      <span className="docs-search-sub-title">{sub.title}</span>
                      <span
                        className="docs-search-sub-excerpt"
                        dangerouslySetInnerHTML={{ __html: sub.excerpt }}
                      />
                    </li>
                  ))}
                </ul>
              )}
            </a>
          ))}
        </div>

        <div className="docs-search-footer">
          <span>Press <kbd>esc</kbd> to close</span>
          <span>Powered by Pagefind</span>
        </div>
      </div>
    </div>
  );

  return (
    <>
      <button type="button" className="docs-search-trigger" onClick={openModal}>
        <span className="docs-search-trigger-icon" aria-hidden="true">
          <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="9" cy="9" r="6" />
            <path d="m17 17-3.5-3.5" strokeLinecap="round" />
          </svg>
        </span>
        <span className="docs-search-trigger-label">Search docs...</span>
        <kbd className="docs-search-trigger-kbd">{shortcutLabel}</kbd>
      </button>
      {typeof document !== "undefined" && modal ? createPortal(modal, document.body) : null}
    </>
  );
}

export default SearchModal;
